### ISSUE TITLE
Should this be added to jumpbox-boshrelease and/or toolbelt?

### ISSUE THREAD

**Issue by geofffranks** [thomasmmitchell/cfseeker#1]

**Comment by thomasmitchell** [comment]
I would say definitely not toolbelt, but jumpbox boshrelease _might_ eventually make sense. Only problem is that the app requires configuration to some specific CF/BOSH, such that it makes a lot of sense being deployed as a CF app itself.

**Comment by geofffranks** [comment]
👍
